// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPyxXGKa9QEwWrMb6JYgM3YdaX5_VZv0',
    appId: '1:777227338765:web:c5a398dcfc5c183aa84144',
    messagingSenderId: '777227338765',
    projectId: 'bloodcamp-32504',
    authDomain: 'bloodcamp-32504.firebaseapp.com',
    storageBucket: 'bloodcamp-32504.firebasestorage.app',
    measurementId: 'G-8WFDLQ2LNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HGOo6crv4Y5dwN9f4Im5E7vnEglGoag',
    appId: '1:777227338765:android:ed66d046ecda3ad0a84144',
    messagingSenderId: '777227338765',
    projectId: 'bloodcamp-32504',
    storageBucket: 'bloodcamp-32504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-n3TiKSsJmuB_yPG-NQ25vLrHW_G-4w',
    appId: '1:777227338765:ios:c968b04f4f9ad2d3a84144',
    messagingSenderId: '777227338765',
    projectId: 'bloodcamp-32504',
    storageBucket: 'bloodcamp-32504.firebasestorage.app',
    iosBundleId: 'com.example.mishasModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-n3TiKSsJmuB_yPG-NQ25vLrHW_G-4w',
    appId: '1:777227338765:ios:c968b04f4f9ad2d3a84144',
    messagingSenderId: '777227338765',
    projectId: 'bloodcamp-32504',
    storageBucket: 'bloodcamp-32504.firebasestorage.app',
    iosBundleId: 'com.example.mishasModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrPyxXGKa9QEwWrMb6JYgM3YdaX5_VZv0',
    appId: '1:777227338765:web:02b96e0219f6e8d2a84144',
    messagingSenderId: '777227338765',
    projectId: 'bloodcamp-32504',
    authDomain: 'bloodcamp-32504.firebaseapp.com',
    storageBucket: 'bloodcamp-32504.firebasestorage.app',
    measurementId: 'G-PB0K2KH447',
  );
}
